---
- name: Setup Stream Web Server
  hosts: localhost
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present
        update_cache: yes

    - name: Build Docker image for ffmpeg
      docker_image:
        name: ffmpeg_stream_processor
        path: ../docker
        state: present

    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: Create directory for FFmpeg output
      file:
        path: /usr/share/nginx/html
        state: directory
        mode: '0755'

    - name: Run Docker container for ffmpeg
      docker_container:
        name: ffmpeg_container
        image: ffmpeg_stream_processor
        ports:
          - "80:80"
        volumes:
          - /usr/share/nginx/html:/usr/share/nginx/html
        state: started

    - name: Copy NGINX configuration file
      copy:
        src: ../nginx/nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: Restart NGINX
      service:
        name: nginx
        state: restarted

